version: '3.3'

services:
  postgres-tokentirr:
    image: postgres:14.4
    container_name: postgres-tokentirr
    ports:
      - '5436:5436'
    expose:
      - '5436'
    restart: unless-stopped
    volumes:
      - ./databases/postgres/:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=tokentirr
      - POSTGRES_PASSWORD=tokentirr
      - POSTGRES_DB=tokentirrdb
      - POSTGRES_PORT=5436
    networks:
      - nginxproxy_net3
    command:
      - '-p 5436'

networks:
  nginxproxy_net3:
    external:
      name: nginxproxy_net3
